### ISSUE TITLE
Issue with MS SQL? - Module fails.

### ISSUE THREAD

**Issue by jgcracknell** [netspotau/moodle-mod_lightboxgallery#16]
Hi

Firstly thanks for your time and effort moving Moodle on.  Problem is - installs fine, and I can add in a Gallery.  Yet when I go into the Gallery this database error appears.MS SQL Server 2008 R2, Win Server 2008R2 IIS7.5 google chrome browser

Notice: Undefined variable: meta in C:\inetpub\wwwroot\moodle\mod\lightboxgallery\view.php on line 80 Notice: Undefined variable: heading in C:\inetpub\wwwroot\moodle\mod\lightboxgallery\view.php on line 81
SHOWING GALLERY: GRAPHIC RESOURCES
Graphics

Error reading from database

More information about this error

Debug info: SQLState: 42000<br>
Error Code: 306<br>
Message: [Microsoft][SQL Server Native Client 10.0][SQL Server]The text, ntext, and image data types cannot be compared or sorted, except when using IS NULL or LIKE operator.<br>

SELECT TOP 10 description
FROM mdl_lightboxgallery_image_meta
WHERE gallery = 1
AND metatype = 'tag'
GROUP BY description
ORDER BY COUNT(description) DESC,
description ASC
[array (
)]
Stack trace:
line 394 of \lib\dml\moodle_database.php: dml_read_exception thrown
line 252 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
line 368 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
line 773 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
line 807 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
line 135 of \mod\lightboxgallery\view.php: call to sqlsrv_native_moodle_database->get_records_sql()

**Comment by aolley** [comment]
Closing this as its reported in:
https://github.com/netspotau/moodle-mod_lightboxgallery/issues/21
