### ISSUE TITLE
DB Error

### ISSUE THREAD

**Issue by jgcracknell** [netspotau/moodle-mod_lightboxgallery#21]
Can create a gallery - but when I enter it to try and add something this error appears

Debug info: SQLState: 42000<br>
Error Code: 8127<br>
Message: [Microsoft][SQL Server Native Client 10.0][SQL Server]Column "mdl_lightboxgallery_image_meta.description" is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP BY clause.<br>

SELECT TOP 10 CONVERT(varchar, description, 32)
FROM mdl_lightboxgallery_image_meta
WHERE gallery = 1
AND metatype = 'tag'
GROUP BY CONVERT(varchar, description, 32)
ORDER BY COUNT( CONVERT(varchar, description, 32)) DESC,
description ASC
[array (
)]
Stack trace:
line 394 of \lib\dml\moodle_database.php: dml_read_exception thrown
line 252 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
line 368 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
line 773 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
line 807 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
line 136 of \mod\lightboxgallery\view.php: call to sqlsrv_native_moodle_database->get_records_sql()

**Comment by aolley** [comment]
I believe this was fixed some time ago in:
https://github.com/netspotau/moodle-mod_lightboxgallery/commit/aa1d08f5b758cd9f8dcca8b9ffe5d276fabd235f
