### ISSUE TITLE
Can't delete CAPTION !?

### ISSUE THREAD

**Issue by xaero7** [netspotau/moodle-mod_lightboxgallery#51]
With moodle 2.3, lightboxgallery CAN delete images files correctly, but it CANNOT delete the records with `metatype`='caption' in the table `lightboxgallery_image_meta `!

**Comment by aolley** [comment]
Hi xaero7,

I've updated the master branch with a fix for this:
https://github.com/netspotau/moodle-mod_lightboxgallery/commit/46305db37799e001f6a9cb88015fc5876b79c04e
