### ISSUE TITLE
Crop option removed from dropdown but access still exists via tab

### ISSUE THREAD

**Issue by timgus** [netspotau/moodle-mod_lightboxgallery#54]
The crop option for lightbox is removed from the dropdown selection:

```php
imageclass.php:                        '<!--<option value="crop">'.get_string('edit_crop', 'lightboxgallery').'</option>-->'.
```

However, it can still be accessed when selecting one of the other edit options and accessed via tab. Would it be possible to remove the crop tab as well until it's fixed?

**Comment by aolley** [comment]
Hi timgus,

I've added the following commit to the master branch which removes the crop tab:
https://github.com/netspotau/moodle-mod_lightboxgallery/commit/aaf74ae5f1cb74acce0a696adcba09f1c0daaf56
