### ISSUE TITLE
Images included in module description not included in backup/restore

### ISSUE THREAD

**Issue by nmet** [netspotau/moodle-mod_lightboxgallery#56]
Hi,
if an image is included in the module description it is not included when the course is backed up and restored. Images in the gallery are included in the backup OK. Using Moodle 2.51

**Comment by aolley** [comment]
Hi nmet,

I've just pushed up a fix for this onto the master branch:
https://github.com/netspotau/moodle-mod_lightboxgallery/commit/7d039edf69690e4e812cbc19e3199c101cb2a343
