### ISSUE TITLE
Black background in thumbnails with transparent background

### ISSUE THREAD

**Issue by s-cenni** [netspotau/moodle-mod_lightboxgallery#63]
When I upload an image with transparent blackground like this http://openclipart.org/image/800px/svg_to_png/25386/Anonymous_Architetto_--_Cani_e_gatti.png
the thumbnail generated has black background, while the image is correctly shown with white background.

The thumbnail:
![image](https://cloud.githubusercontent.com/assets/4058151/3411944/2cb62458-fdf9-11e3-81e8-fcc48d7f3dc4.png)

**Comment by aolley** [comment]
Hi s-cenni,

I've just added a fix for this to the master branch:
https://github.com/netspotau/moodle-mod_lightboxgallery/commit/cdb34c019a976c2f8df81c138a9e877ff3bb9499

You can apply that change to your instance to fix the issue.
