### ISSUE TITLE
image shift while looking at image by clicking it

### ISSUE THREAD

**Issue by cperves** [netspotau/moodle-mod_lightboxgallery#69]
Hello,
While using clean theme
While looking at image by clicking it in the popup like window is too hight
 on the page, passing behing page header (navigation bar,...) see image below
![too-high](https://cloud.githubusercontent.com/assets/1996913/8408889/fa50e61e-1e73-11e5-8620-53ee10040491.png)

if you change L.381 of mod/lightbioxgallery/yui/lightbox.js with 
var lightboxTop = Y.DOM.docScrollY() + Y.one('header').get('clientHeight') + border*2,

it is resolved

Hope it will help

**Comment by aolley** [comment]
I've put in a fix for this by adjusting the z-index of the lightbox so the navbar is behind it.
