### ISSUE TITLE
accent encoding error into edit form

### ISSUE THREAD

**Issue by OctaveBabel** [netspotau/moodle-mod_lightboxgallery#70]
into "mod_form.php" (l. 88) : strtolower function cause accent encoding error (ex : obvious into french)
prefer to use mb_strtolower function instead which is more reliable

**Comment by aolley** [comment]
Hi @OctaveBabel,

Thanks for the report. I've just pushed a [commit](https://github.com/netspotau/moodle-mod_lightboxgallery/commit/eab36155a8c1f502bee97d4c45b7f597e1a6edfb) that switches the strtolower functions used to the core moodle text class which uses mb_strtolower when available.
