### ISSUE TITLE
Query for lightboxgallery to support global search

### ISSUE THREAD

**Issue by yukito8000** [netspotau/moodle-mod_lightboxgallery#73]
Hi Adam. Many thanks for providing this plugin to the community; its functionality is really appreciated by our staff and students, and we’re really grateful to you for your efforts to maintain and update it.

On that note, please could I quickly query whether you have any plans to update the plugin to be fully compatible with Moodle v3.1, and its new Global Search feature in particular? To clarify: while we’ve tested the Lightbox Gallery plugin under v3.1 and all of the core functionality seems to work fine, we’ve found that instances of the activity are not searchable via v3.1’s Global Search feature. Please see the following screenshot for details, which lists all of the available areas that can searched under v3.1 (note that these settings are available via: Site Administration -> Plugins -> Search -> Manage Global Search):

http://imgur.com/lWWQByE

Note also that the above screenshot was taken on a v3.1 system where the Lightbox Gallery plugin is installed and available. However, as you can see, the Lightbox Gallery activity is not listed as being available to be searched. Obviously, this is likely to be a significant problem/cause of confusion for users who might want to search for specific instances of the Lightbox Gallery activity across Moodle.

I’m not a developer, but my understanding is that mod plugins can be made searchable relatively easily via the addition of a new search class within the plugin’s codebase (located at ../classes/search/activity.php). Please see the following for further details:

https://moodle.org/mod/forum/discuss.php?d=334938
https://docs.moodle.org/31/en/Global_search
https://docs.moodle.org/dev/Search_API

We really hope this search capability can be added to Lightbox Gallery as I’m sure it would be a huge benefit to our users (as well as those of other v3.1 systems) and, again, many thanks for all your efforts to develop this plugin and share it with the community.

Best wishes,
Lina

**Comment by aolley** [comment]
Hi Lina,

I do in fact intend to add global search support to the plugin - just haven't had the time to get to it yet. I'll likely be able to get to this over the next week or so.

**Comment by yukito8000** [comment]
Hi Adam,
Thanks a lot for all your great contributions and we'll be looking forward to the new release.
Best wishes,
Lina

**Comment by aolley** [comment]
This has now been added, v2.8.0.7 has been tagged and released on moodle.org.

**Comment by yukito8000** [comment]
Hi Adam,
Many thanks for the quick update. We really appreciate your great help. I will download the new release from moodle.org and install it on our server.
Best wishes,
Lina
