### ISSUE TITLE
Admin pages: Error 500

### ISSUE THREAD

**Issue by jfrickard** [netspotau/moodle-mod_lightboxgallery#75]
I have just upgraded my site to Moodle 3.1, upgrading the module to v2.8.0.9 from the github repo.

When trying to get into the /admin pages now I get an error 500... remove the module folder, I get to the Plugins Requiring Attention page saying the folders missing on disk... put it back and I get an error 500.

PHP7.0
Ubuntu 16
Moodle 3.1
MOODLE_31_STABLE branch of module

**Comment by aolley** [comment]
Are you able to provide more detail of the error from the error log?
