### ISSUE TITLE
Rotation and flipping problems seen in Moodle 3.0, 3.2, 3.3

### ISSUE THREAD

**Issue by oelker** [netspotau/moodle-mod_lightboxgallery#76]
In the editing screen, after you rotate or flip once, on subsequent flips or rotations the preview image doesn't update to reflect the next change. But if you then go back to the gallery view, you can see that the change has been made. This is misleading to users; causes them to continue clicking because they can't see the changes. 

We quickly ran through this in Clean, Boost, and Essential on at least 3.3, and saw it in Essential on 3.0 and 3.2.

**Comment by oelker** [comment]
Oh BTW we turned on debugging when testing this in 3.3 and we didn't get any error message from this. We did when we tried clicking "rotate" or "flip" without selecting which action to do, quite reasonably. But no error message when the image in the editing screens didn't refresh to show us that the flip or rotation had happened as we directed. Thanks!

**Comment by aolley** [comment]
I'm currently unable to reproduce this issue on v2.8.0.9 of the plugin on Moodle 3.3 using the boost theme or v3.3.0.1 of the essential theme.

Are you able to provide more details of your environment? It sounds like something might be caching the rotated image that is generated after the first edit action when it shouldn't be.

**Comment by oelker** [comment]
Yeah, it does sound like that, and I'm not sure how to diagnose Sure, let me tell you what about at least the Moodle 3.3 version we were using, and ping  @mackensen to see what more he can say about it. (Some of the other tests were done by the person sitting next to me who was using her instances that I don't have access to, at a different college.) 

Moodle 3.3+ build 20170608
php 5.6.29.0.8.1
mysql 5.5.53-0+deb8u1

What other sorts of attributes and settings would it be good to know about? I'll get more eyes on this (it's the final few hours of [Hack/Doc summer 2017](http://www.clamp-it.org/clamp-events/moodle-hackdoc-fest-summer-2017/)) and see what else I can find.

**Comment by mackensen** [comment]
I can reproduce in one test environment, but not another. They're both fairly generic 3.3 test environments; I'll see if I can narrow it down.
