### ISSUE TITLE
Core Moodle 3.3 unit tests fail

### ISSUE THREAD

**Issue by azrek** [netspotau/moodle-mod_lightboxgallery#77]
Moodle version: 2017051500.10
DB: psql (PostgreSQL) 9.5.7
OS: Linux 16.04
lightboxgallery version: 2017050300

We are upgrading to Moodle 3.3 and get the following unit test errors with the latest plagairism_turnitin plugin:

1) core_calendar_container_testcase::test_delete_module_delete_events
coding_exception: Coding error detected, it must be fixed by a programmer: Component mod_lightboxgallery does not support generators yet. Missing tests/generator/lib.php.

/home/clients/moodle/lib/testing/generator/data_generator.php:121
/home/clients/moodle/lib/testing/generator/data_generator.php:500
/home/clients/moodle/calendar/tests/container_test.php:299
/home/clients/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit core_calendar_container_testcase calendar/tests/container_test.php

ERRORS!

So we skipped the core unit test above and continued only to get this error:

1) search_manager_testcase::test_search_areas
Unexpected debugging() call detected.
Debugging: Class 'core_search\area\base_activity' has been renamed for the autoloader and is now deprecated. Please use 'core_search\base_activity' instead.
* line 117 of /lib/classes/component.php: call to debugging()
* line ? of unknownfile: call to core_component::classloader()
* line 36 of /mod/lightboxgallery/classes/search/activity.php: call to spl_autoload_call()
* line 111 of /lib/classes/component.php: call to include_once()
* line ? of unknownfile: call to core_component::classloader()
* line ? of unknownfile: call to spl_autoload_call()
* line 942 of /lib/classes/component.php: call to class_exists()
* line 241 of /search/classes/manager.php: call to core_component::get_component_classes_in_namespace()
* line 77 of /search/tests/manager_test.php: call to core_search\manager::get_search_areas_list()
* line ? of unknownfile: call to search_manager_testcase->test_search_areas()
* line 1085 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to ReflectionMethod->invokeArgs()
* line 936 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit_Framework_TestCase->runTest()
* line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit_Framework_TestCase->runBare()
* line 701 of /vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
* line 892 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit_Framework_TestResult->run()
* line 753 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestCase->run()
* line 753 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 753 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 465 of /vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit_Framework_TestSuite->run()
* line 185 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit_TextUI_TestRunner->doRun()
* line 115 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit_TextUI_Command->run()
* line 47 of /vendor/phpunit/phpunit/phpunit: call to PHPUnit_TextUI_Command::main()

/home/clients/moodle/lib/phpunit/classes/advanced_testcase.php:88

To re-run:
 vendor/bin/phpunit search_manager_testcase search/tests/manager_test.php

ERRORS!

**Comment by aolley** [comment]
Thanks for the report, I actually noticed these myself but it was a lower priority thing at the time.

I'll have an updated version sometime today I think (now that its in writing, I *have* to do it ;))

**Comment by azrek** [comment]
cheers @aolley  !

**Comment by aolley** [comment]
I've just released v3.2.0.1 of the plugin which addresses these two issues:
https://moodle.org/plugins/pluginversion.php?id=14375

All core unit tests now pass for me with lightboxgallery installed at that version. Let me know if you see different :)
