### ISSUE TITLE
Branch for Moodle 3.2 Stable

### ISSUE THREAD

**Issue by ruddj** [netspotau/moodle-mod_lightboxgallery#78]
Good Day,
 First thanks for all your efforts in maintaining the Lightbox Gallery Mod.

We are just upgrading to Moodle 3.2 and we use GIT for maintaining our plugins. At present we track the MOODLE_31_STABLE branch but at present there is no 3.2 or 3.3 branch to track, only master. I usually try to avoid tracking master as often it breaks things in the future when updated for newer Moodle versions. 

The Moodle Plugin site lists 3.2.0.1 as the latest stable release, but this appears to only be available in the Master branch. Could you please create a MOODLE_32_STABLE or MOODLE_33_STABLE branch that we could track?

Thankyou,
 James

**Comment by aolley** [comment]
Seems reasonable to me. I've just branched off master to MOODLE_32_STABLE. Enjoy!

**Comment by ruddj** [comment]
Thanks Adam.
