### ISSUE TITLE
Notice when I try to add an image

### ISSUE THREAD

**Issue by s-cenni** [netspotau/moodle-mod_lightboxgallery#83]
When I try to add an image I get this notice:

Notice: Trying to get property of non-object in /var/www/html/test/mod/lightboxgallery/imageadd_form.php on line 93

The problem is in this line:
`return !in_array($gallery->autoresize, array(AUTO_RESIZE_UPLOAD, AUTO_RESIZE_BOTH));`
because gallery is an array type

**Comment by aolley** [comment]
Thanks for the report. I've fixed that in master now and will be pushing a patch release out to moodle.org shortly.

**Comment by s-cenni** [comment]
Thank you!
