### ISSUE TITLE
Update MOODLE_33_STABLE Branch

### ISSUE THREAD

**Issue by ruddj** [netspotau/moodle-mod_lightboxgallery#84]
Good Day,
 With the 3.3.0.6 release the 3.3 branch no longer has the most recent version that is in Moodle repository.

Could the MOODLE_33_STABLE branch please be updated?
Also would it be possible to create a MOODLE_34_STABLE  MOODLE_35_STABLE branch?

Thank you,
 James

**Comment by aolley** [comment]
I've updated the MOODLE_33_STABLE branch.
Given there is no difference between MOODLE_33_STABLE and master - I'm not inclined to bother creating those branches. master can just be used in their place.
