### ISSUE TITLE
Restore PHP notice: ...must define the function get_other_mapping()

### ISSUE THREAD

**Issue by PickledKitty** [netspotau/moodle-mod_lightboxgallery#86]
Upon restoring a course in Moodle 3.3.6, got this PHP notice: In order to restore course logs accurately the event "mod_lightboxgallery\event\gallery_comment_created" must define the function get_other_mapping().
User id "84420" could not be mapped. Skipping log record.

**Comment by aolley** [comment]
I've just fixed this in c2b9fac - it'll be included in the next release.
