### ISSUE TITLE
Fatal error: imagecreatefromstring(): gd-png: fatal libpng error: Read Error: truncated data in /srv/http/moodle/mod/lightboxgallery/imageclass.php on line 302

### ISSUE THREAD

**Issue by rochelmeyer** [netspotau/moodle-mod_lightboxgallery#88]
This error breaks the whole page in one specific moodle-course. Lightbox Gallerys in several other courses are not affected and work as expected. 
![Screenshot_20190610_182647](https://user-images.githubusercontent.com/14875217/59210349-af68e100-8bad-11e9-94bc-5b3594fb2650.png)
Changing the theme (back to boost) did not resolve the issue.

**Comment by aolley** [comment]
Over a year past you posted this, my apologies - but this looks like it could be related to a bug in libgd or php that has since been resolved. Does a newer version of php resolve the issue for you?

**Comment by rochelmeyer** [comment]
Yes, absolutely. We do not see this error anymore. Anyway, Thanks for your Efforts! Closing this now.
