### ISSUE TITLE
Error in lightbox gallery

### ISSUE THREAD

**Issue by alexanderNG** [netspotau/moodle-mod_lightboxgallery#91]
Hi, I use latest version of Moodle and lightbox gallery. Suddenly, when working with a file, I received a diagnostic
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 49152 bytes) in /var/www/vhosts/u0172359.plsk.regruhosting.ru/httpdocs/moodle/mod/lightboxgallery/imageclass.php on line 302
Thank you in advance

**Comment by aolley** [comment]
The image you're editing must large enough to be causing GD to run out of memory when working with it.

I've added a commit to master (9d55e47) to increase the memory limit when resizing.
